### ISSUE TITLE
The message which is not sending to assigned number in  settings page

### ISSUE THREAD

**Issue by csanthosh** [thebachchaoproject/i-rode#1]
Steps to reproduce the bug:

1. Launch the application from the mobile
2. Tap on the settings option
3. Make it to send the message from third contact field by using back end of the application 
4. Tap on the send message option

Actual result: The message is not sending to the assigned number in third field 

Expected result: The massage should send to the Assigned numbers in the setting page

**Comment by chinmayisk** [comment]
closing this since it has been solved
